USE museumdb;

ALTER TABLE Department
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Artist
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Exhibition
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Artwork
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Gift_Shop_Item
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Food
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Membership
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Employee
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Event
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Institution
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);

ALTER TABLE Tour
  ADD COLUMN IF NOT EXISTS Image_URL VARCHAR(255);
